### ISSUE TITLE
Seems ViewOnYP failed to work now

### ISSUE THREAD

**Issue by Karim-shy** [TheLastZombie/userscripts#16]
I tried to move the cursor on top of the purchase button (like in the presentation vedio) but nothing pops up, I tried fanbox, fantia and patreon they all failed to work/(ㄒoㄒ)/~~

**Comment by TheLastZombie** [comment]
Are there any errors in the browser console? Could you share some of the pages you tried?

Also,  keep in mind that:
- the overlay only shows up when the respective artist can be found on at least one supported site (i. e. Kemono)
- you don't have to hover over any buttons, if the above condition is met, the overlay will always show up at the bottom center of the window (that's just where the button happened to be in the preview)

**Comment by TheLastZombie** [comment]
Feel free to reopen if this is still relevant.
